/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analysis;

import java.util.ArrayList;

/**
 *
 * @author s4979389
 */
public class InvestmentAnalysisProgram extends javax.swing.JFrame {

    /**
     * Creates new form InvestmentAnalysisProgram
     */
    public InvestmentAnalysisProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        fixedExpField = new javax.swing.JTextField();
        varExpField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        displayStatsButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        addBusinessButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        initCapField = new javax.swing.JTextField();
        yearsField = new javax.swing.JTextField();
        profitField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        resultArea = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 450));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel6.setText("Most Profitable Business Data and ROI Year");

        jLabel1.setText("Initial Capital");

        jLabel2.setText("Years to Analyse");

        displayStatsButton.setText("Display Business Statistics");
        displayStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayStatsButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Profit Margin");

        addBusinessButton.setText("Add New Business");
        addBusinessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBusinessButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Fixed Expense");

        jLabel5.setText("Variable Expense");

        initCapField.setPreferredSize(new java.awt.Dimension(10, 25));

        yearsField.setMinimumSize(new java.awt.Dimension(10, 25));
        yearsField.setPreferredSize(new java.awt.Dimension(10, 25));

        jLabel7.setText("Business Analysis Results");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        resultArea.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(initCapField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearsField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profitField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fixedExpField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel5))
                            .addComponent(varExpField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBusinessButton))
                    .addComponent(displayStatsButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(resultArea, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fixedExpField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varExpField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profitField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(initCapField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBusinessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(displayStatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultArea, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayStatsButtonActionPerformed

        for (int i = 0; i < busInfo.size(); i++) {
            jTextArea1.append("--------------------\n");
            jTextArea1.append(String.format("%s%d\n", "Currently Analysing Business #", i));
            jTextArea1.append("--------------------\n");
            jTextArea1.repaint();
            calBusFinNums(busInfo.get(i), invCap, numYears);

        }
    }//GEN-LAST:event_displayStatsButtonActionPerformed

    private void addBusinessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBusinessButtonActionPerformed
        getUserInput();
    }//GEN-LAST:event_addBusinessButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvestmentAnalysisProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvestmentAnalysisProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvestmentAnalysisProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvestmentAnalysisProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvestmentAnalysisProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBusinessButton;
    private javax.swing.JButton displayStatsButton;
    private javax.swing.JTextField fixedExpField;
    private javax.swing.JTextField initCapField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField profitField;
    private javax.swing.JScrollPane resultArea;
    private javax.swing.JTextField varExpField;
    private javax.swing.JTextField yearsField;
    // End of variables declaration//GEN-END:variables

    // initialize variables
    int numYears = 0; //number of years for analysis
    float invCap = 0; //initial investm System.out.println("--------------------");
//      System.out.printf("%s%d\n", "Currently Analysing Business #", i);
//      System.out.println("--------------------");ent capital

    ArrayList<float[]> busInfo = new ArrayList<float[]>(); //information on businesses

    /**
     * This method prompts the user to enter information for the businesses
     *
     * @param float [4] b reference to newly created float array of size 4
     * passed * by reference to the function
     * @param int busNum represents the number of businesses;
     */
    public void getUserInput() {
        invCap = Float.parseFloat(initCapField.getText());
        numYears = Integer.parseInt(yearsField.getText());
        float profitMargin = Float.parseFloat(profitField.getText());
        float fixedExp = Float.parseFloat(fixedExpField.getText());
        float varExp = Float.parseFloat(varExpField.getText());

        //[0] = profit margin
        //[1] = fixed expenses
        //[2] = variable expenses
        //[3] = endBalance after analyses//add to busInfo Array
        float business[] = {profitMargin, fixedExp, varExp, 0};

        busInfo.add(business);//add to businesses
        System.out.println("Business added");
    }

    /**
     * Performs and reports the financial analysises on a business achieve
     *
     * @param float [] business array containng the information about the
     * business in this order index [0] = profit margin, [1] = fixed expense,
     * [2] = variable expense and [3] = endBalance
     * @param float cap initial investment capital of the business
     * @param int yrs the number of years to analyse the business
     */
    public void calBusFinNums(float business[], float cap, int yrs) {
        float gross = 0;
        float net = 0;
        String output = "";

        for (int i = 0; i < yrs; i++) {
            output = String.format("%s%d%s\n", "Year: ", i, " analysis");
            output += String.format("%s%.2f\n", "Gross Profit: ", gross = cap * business[0]);
            output += String.format("%s%.2f\n", "Net Profit: ", net = gross - business[1] - (business[2] * cap));//update netprofit
            output += String.format("%s%.2f\n", "End balance: ", cap += net);//endBalance  = updated investment Cap

            jTextArea1.append(output);
        }
        jTextArea1.repaint();
        //store ending balance
        business[3] = cap;
    }

    /**
     * Takes the information for a single businesses and calculates the number
     * of years it takes to reach 100% ROI. achievegist
     *
     * @param float [] business array containng the information about the
     * business in this order index [0] = profit margin, [1] = fixed expense,
     * [2] = variable expense and [3] = endBalance
     * @param float cap initial investment capital for the business
     * @return int years number of years it took to reach 100% ROI
     */
    public static int findROIYr(float[] business, float cap) {
        float gross = 0, net = 0, sumNet = 0;
        int years = 0;

        while ((sumNet / cap) < 1) {
            gross = cap * business[0];
            net = gross - business[1] - (business[2] * cap);
            sumNet += net;
            years++;
        }

        return years;
    }

    /**
     * Finds the most profitable business amongst the given array list by
     * coparing the values in the last index, [3] = end balance i.e investment
     * capital + total net profit at the end of the given years
     *
     * @param busInfo
     * @return int winner the index of the business with the largest end balance
     */
    public static int findMostProf(ArrayList<float[]> busInfo) {
        int winner = 0;
        for (int i = 0; i < busInfo.size() - 1; i++) {
            if (busInfo.get(i)[3] < busInfo.get(i + 1)[3]) {
                winner = i;
            }
        }
        return winner;
    }

}
